# Generated by Django 5.1.1 on 2026-06-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Analysis', max_length=200)),
                ('requirements_text', models.TextField()),
                ('accuracy_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('warning', 'Warning')], max_length=20)),
                ('message', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='core.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('preconditions', models.TextField()),
                ('steps_json', models.TextField()),
                ('expected_result', models.TextField()),
                ('scenario_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('edge', 'Edge Case')], default='positive', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='core.analysissession')),
            ],
        ),
    ]
