# Generated by Django 5.1.1 on 2026-06-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_analysissession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedtestcase',
            name='steps_done',
            field=models.TextField(default='[]'),
        ),
        migrations.CreateModel(
            name='WorkspaceDraftInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_draft_inputs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_inputs', to='core.workspace')),
            ],
            options={
                'ordering': ['updated_at'],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
