# Generated by Django 5.1.1 on 2026-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_detailedtestcase_steps_done_workspacedraftinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testscenario',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='testscenario',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
