# Generated by Django 5.1.1 on 2026-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_testscenario_user_rating_testscenario_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcondition',
            name='requirement_ref',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
